export enum Feature {
  OWNER = 'OWNER',

  ADMIN = 'ADMIN',

  CREATE_REGISTER_INVITE = 'CREATE_REGISTER_INVITE',

  GET_PATH_POINT = 'GET_PATH_POINT',
  CREATE_PATH_POINT = 'CREATE_PATH_POINT',
  UPDATE_PATH_POINT = 'UPDATE_PATH_POINT',
  DELETE_PATH_POINT = 'DELETE_PATH_POINT',

  GET_EXPLORATION_ROLE = 'GET_EXPLORATION_ROLE',
  CREATE_EXPLORATION_ROLE = 'CREATE_EXPLORATION_ROLE',
  UPDATE_EXPLORATION_ROLE = 'UPDATE_EXPLORATION_ROLE',
  DELETE_EXPLORATION_ROLE = 'DELETE_EXPLORATION_ROLE',
}
