export enum Feature {
  OWNER = 'OWNER',

  ADMIN = 'ADMIN',

  CREATE_REGISTER_INVITE = 'CREATE_REGISTER_INVITE',

  GET_PATH_POINT = 'GET_PATH_POINT',
  CREATE_PATH_POINT = 'CREATE_PATH_POINT',
  UPDATE_PATH_POINT = 'UPDATE_PATH_POINT',
  DELETE_PATH_POINT = 'DELETE_PATH_POINT',

  GET_EXPLORATION_ROLE = 'GET_EXPLORATION_ROLE',
  CREATE_EXPLORATION_ROLE = 'CREATE_EXPLORATION_ROLE',
  UPDATE_EXPLORATION_ROLE = 'UPDATE_EXPLORATION_ROLE',
  DELETE_EXPLORATION_ROLE = 'DELETE_EXPLORATION_ROLE',

  GET_EXPLORATION_PERMISSION = 'GET_EXPLORATION_PERMISSION',
  CREATE_EXPLORATION_PERMISSION = 'CREATE_EXPLORATION_PERMISSION',
  UPDATE_EXPLORATION_PERMISSION = 'UPDATE_EXPLORATION_PERMISSION',
  DELETE_EXPLORATION_PERMISSION = 'DELETE_EXPLORATION_PERMISSION',

  GET_USER_EXPLORATION_ROLE = 'GET_USER_EXPLORATION_ROLE',
  UNASSIGN_USER_EXPLORATION_ROLE = 'UNASSIGN_USER_EXPLORATION_ROLE',
  SET_USER_EXPLORATION_ROLES = 'SET_USER_EXPLORATION_ROLES',
}
