FROM nginx:latest
# look into alpine and see if it's smaller

COPY nginx/default /etc/nginx/conf.d/default.conf

RUN mkdir -p /var/www/html

COPY frontend/dist/kumo/browser/* /var/www/html/.

EXPOSE 80/tcp

# Configure logs
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
