/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Object to create a register invite
 */
export interface CreateRegisterInviteRequest { 
    /**
     * Specifies for how long the invite should be valid, 0 for unlimited
     */
    validitySeconds: number;
    /**
     * Number of uses, 0 for unlimited
     */
    uses: number;
}

