/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Explorer result file model
 */
export interface ExplorerFileModel { 
    name?: string;
    fullPath?: string;
    type?: ExplorerFileModel.TypeEnum;
    write: boolean;
    _delete: boolean;
    modifyRoot: boolean;
}
export namespace ExplorerFileModel {
    export type TypeEnum = 'DIRECTORY' | 'IMAGE' | 'FILE';
    export const TypeEnum = {
        DIRECTORY: 'DIRECTORY' as TypeEnum,
        IMAGE: 'IMAGE' as TypeEnum,
        FILE: 'FILE' as TypeEnum
    };
}


